package design

import (
	. "github.com/goadesign/goa/design/apidsl"
)

// Observation is the observation resource media type------------------------------------------------------------------------------------------------
var ObservationPayload = Type("ObservationPayload", func() {
	Reference(Observation)
	Attribute("identifier")
	Attribute("status")
	Attribute("category")
	Attribute("code")
	Attribute("encounter")
	Attribute("effectiveDateTime")
	Attribute("effectivePeriod")
	Attribute("issued")
	Attribute("performer")
	Attribute("effectiveDateTime")

	Attribute("valueQuantity")
	Attribute("valueCodeableConcept")
	Attribute("valueString")
	Attribute("valueRange")
	Attribute("valueSampledData")
	Attribute("valueAttachment")
	Attribute("valueTime")
	Attribute("valueDatTime")
	Attribute("valuePeriod")

	Attribute("dateAbsentReason")
	Attribute("interpretation")
	Attribute("comments")
	Attribute("bodySite")
	Attribute("method")
	Attribute("specimen")
	Attribute("device")
	Attribute("referenceRange")
	Attribute("related")
	Attribute("component")
})
var ReferenceRangePayload = Type("ReferenceRangePayload", func() {
	Reference(ReferenceRange)
	Attribute("low")
	Attribute("high")
	Attribute("meaning")
	Attribute("age")
	Attribute("text")
})
var RelatedPayload = Type("RelatedPayload", func() {
	Reference(Related)
	Attribute("type")
	Attribute("target")
})
var ComponentPayload = Type("ComponentPayload", func() {
	Reference(Component)
	Attribute("code")
	Attribute("valueQuantity")
	Attribute("valueCodeableConcept")
	Attribute("valueRange")
	Attribute("valueSampledData")
	Attribute("valueAttachment")
	Attribute("valueTime")
	Attribute("valueDatTime")
	Attribute("valuePeriod")
	Attribute("dataAbsentReason")
	Attribute("referenceRange")
})
