// Code generated by goagen v1.1.0-dirty, command line:
// $ goagen
// --design=github.com/goa-fhir/server/design
// --out=$(GOPATH)\src\github.com\goa-fhir\server
// --version=v1.1.0-dirty
//
// API "goa-FHIR": oauth2_provider TestHelpers
//
// The content of this file is auto-generated, DO NOT MODIFY

package test

import (
	"bytes"
	"fmt"
	"github.com/goa-fhir/server/app"
	"github.com/goadesign/goa"
	"github.com/goadesign/goa/goatest"
	"golang.org/x/net/context"
	"io"
	"log"
	"net/http"
	"net/http/httptest"
	"net/url"
	"strconv"
	"time"
)

// AuthorizeOauth2ProviderBadRequest runs the method Authorize of the given controller with the given parameters.
// It returns the response writer so it's possible to inspect the response headers and the media type struct written to the response.
// If ctx is nil then context.Background() is used.
// If service is nil then a default service is created.
func AuthorizeOauth2ProviderBadRequest(t goatest.TInterface, ctx context.Context, service *goa.Service, ctrl app.Oauth2ProviderController, contained *string, containedType *string, count *int, elements *string, has *string, id *int, include *string, lastUpdate *time.Time, list *string, profile *string, query *string, revinclude *string, security *string, sort *string, summary *string, tag *string, text *string, type_ *string, clientID string, redirectURI *string, responseType string, scope *string, state *string) (http.ResponseWriter, *app.OAuth2ErrorMedia) {
	// Setup service
	var (
		logBuf bytes.Buffer
		resp   interface{}

		respSetter goatest.ResponseSetterFunc = func(r interface{}) { resp = r }
	)
	if service == nil {
		service = goatest.Service(&logBuf, respSetter)
	} else {
		logger := log.New(&logBuf, "", log.Ltime)
		service.WithLogger(goa.NewLogger(logger))
		newEncoder := func(io.Writer) goa.Encoder { return respSetter }
		service.Encoder = goa.NewHTTPEncoder() // Make sure the code ends up using this decoder
		service.Encoder.Register(newEncoder, "*/*")
	}

	// Setup request context
	rw := httptest.NewRecorder()
	query := url.Values{}
	if contained != nil {
		sliceVal := []string{*contained}
		query["_contained"] = sliceVal
	}
	if containedType != nil {
		sliceVal := []string{*containedType}
		query["_containedType"] = sliceVal
	}
	if count != nil {
		sliceVal := []string{strconv.Itoa(*count)}
		query["_count"] = sliceVal
	}
	if elements != nil {
		sliceVal := []string{*elements}
		query["_elements"] = sliceVal
	}
	if has != nil {
		sliceVal := []string{*has}
		query["_has"] = sliceVal
	}
	if id != nil {
		sliceVal := []string{strconv.Itoa(*id)}
		query["_id"] = sliceVal
	}
	if include != nil {
		sliceVal := []string{*include}
		query["_include"] = sliceVal
	}
	if lastUpdate != nil {
		sliceVal := []string{(*lastUpdate).Format(time.RFC3339)}
		query["_lastUpdate"] = sliceVal
	}
	if list != nil {
		sliceVal := []string{*list}
		query["_list"] = sliceVal
	}
	if profile != nil {
		sliceVal := []string{*profile}
		query["_profile"] = sliceVal
	}
	if query != nil {
		sliceVal := []string{*query}
		query["_query"] = sliceVal
	}
	if revinclude != nil {
		sliceVal := []string{*revinclude}
		query["_revinclude"] = sliceVal
	}
	if security != nil {
		sliceVal := []string{*security}
		query["_security"] = sliceVal
	}
	if sort != nil {
		sliceVal := []string{*sort}
		query["_sort"] = sliceVal
	}
	if summary != nil {
		sliceVal := []string{*summary}
		query["_summary"] = sliceVal
	}
	if tag != nil {
		sliceVal := []string{*tag}
		query["_tag"] = sliceVal
	}
	if text != nil {
		sliceVal := []string{*text}
		query["_text"] = sliceVal
	}
	if type_ != nil {
		sliceVal := []string{*type_}
		query["_type"] = sliceVal
	}
	{
		sliceVal := []string{clientID}
		query["client_id"] = sliceVal
	}
	if redirectURI != nil {
		sliceVal := []string{*redirectURI}
		query["redirect_uri"] = sliceVal
	}
	{
		sliceVal := []string{responseType}
		query["response_type"] = sliceVal
	}
	if scope != nil {
		sliceVal := []string{*scope}
		query["scope"] = sliceVal
	}
	if state != nil {
		sliceVal := []string{*state}
		query["state"] = sliceVal
	}
	u := &url.URL{
		Path:     fmt.Sprintf("/nosh/oauth2/auth"),
		RawQuery: query.Encode(),
	}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		panic("invalid test " + err.Error()) // bug
	}
	prms := url.Values{}
	if contained != nil {
		sliceVal := []string{*contained}
		prms["_contained"] = sliceVal
	}
	if containedType != nil {
		sliceVal := []string{*containedType}
		prms["_containedType"] = sliceVal
	}
	if count != nil {
		sliceVal := []string{strconv.Itoa(*count)}
		prms["_count"] = sliceVal
	}
	if elements != nil {
		sliceVal := []string{*elements}
		prms["_elements"] = sliceVal
	}
	if has != nil {
		sliceVal := []string{*has}
		prms["_has"] = sliceVal
	}
	if id != nil {
		sliceVal := []string{strconv.Itoa(*id)}
		prms["_id"] = sliceVal
	}
	if include != nil {
		sliceVal := []string{*include}
		prms["_include"] = sliceVal
	}
	if lastUpdate != nil {
		sliceVal := []string{(*lastUpdate).Format(time.RFC3339)}
		prms["_lastUpdate"] = sliceVal
	}
	if list != nil {
		sliceVal := []string{*list}
		prms["_list"] = sliceVal
	}
	if profile != nil {
		sliceVal := []string{*profile}
		prms["_profile"] = sliceVal
	}
	if query != nil {
		sliceVal := []string{*query}
		prms["_query"] = sliceVal
	}
	if revinclude != nil {
		sliceVal := []string{*revinclude}
		prms["_revinclude"] = sliceVal
	}
	if security != nil {
		sliceVal := []string{*security}
		prms["_security"] = sliceVal
	}
	if sort != nil {
		sliceVal := []string{*sort}
		prms["_sort"] = sliceVal
	}
	if summary != nil {
		sliceVal := []string{*summary}
		prms["_summary"] = sliceVal
	}
	if tag != nil {
		sliceVal := []string{*tag}
		prms["_tag"] = sliceVal
	}
	if text != nil {
		sliceVal := []string{*text}
		prms["_text"] = sliceVal
	}
	if type_ != nil {
		sliceVal := []string{*type_}
		prms["_type"] = sliceVal
	}
	{
		sliceVal := []string{clientID}
		prms["client_id"] = sliceVal
	}
	if redirectURI != nil {
		sliceVal := []string{*redirectURI}
		prms["redirect_uri"] = sliceVal
	}
	{
		sliceVal := []string{responseType}
		prms["response_type"] = sliceVal
	}
	if scope != nil {
		sliceVal := []string{*scope}
		prms["scope"] = sliceVal
	}
	if state != nil {
		sliceVal := []string{*state}
		prms["state"] = sliceVal
	}
	if ctx == nil {
		ctx = context.Background()
	}
	goaCtx := goa.NewContext(goa.WithAction(ctx, "Oauth2ProviderTest"), rw, req, prms)
	authorizeCtx, err := app.NewAuthorizeOauth2ProviderContext(goaCtx, service)
	if err != nil {
		panic("invalid test data " + err.Error()) // bug
	}

	// Perform action
	err = ctrl.Authorize(authorizeCtx)

	// Validate response
	if err != nil {
		t.Fatalf("controller returned %s, logs:\n%s", err, logBuf.String())
	}
	if rw.Code != 400 {
		t.Errorf("invalid response status code: got %+v, expected 400", rw.Code)
	}
	var mt *app.OAuth2ErrorMedia
	if resp != nil {
		var ok bool
		mt, ok = resp.(*app.OAuth2ErrorMedia)
		if !ok {
			t.Fatalf("invalid response media: got %+v, expected instance of app.OAuth2ErrorMedia", resp)
		}
		err = mt.Validate()
		if err != nil {
			t.Errorf("invalid response media type: %s", err)
		}
	}

	// Return results
	return rw, mt
}

// AuthorizeOauth2ProviderFound runs the method Authorize of the given controller with the given parameters.
// It returns the response writer so it's possible to inspect the response headers.
// If ctx is nil then context.Background() is used.
// If service is nil then a default service is created.
func AuthorizeOauth2ProviderFound(t goatest.TInterface, ctx context.Context, service *goa.Service, ctrl app.Oauth2ProviderController, contained *string, containedType *string, count *int, elements *string, has *string, id *int, include *string, lastUpdate *time.Time, list *string, profile *string, query *string, revinclude *string, security *string, sort *string, summary *string, tag *string, text *string, type_ *string, clientID string, redirectURI *string, responseType string, scope *string, state *string) http.ResponseWriter {
	// Setup service
	var (
		logBuf bytes.Buffer
		resp   interface{}

		respSetter goatest.ResponseSetterFunc = func(r interface{}) { resp = r }
	)
	if service == nil {
		service = goatest.Service(&logBuf, respSetter)
	} else {
		logger := log.New(&logBuf, "", log.Ltime)
		service.WithLogger(goa.NewLogger(logger))
		newEncoder := func(io.Writer) goa.Encoder { return respSetter }
		service.Encoder = goa.NewHTTPEncoder() // Make sure the code ends up using this decoder
		service.Encoder.Register(newEncoder, "*/*")
	}

	// Setup request context
	rw := httptest.NewRecorder()
	query := url.Values{}
	if contained != nil {
		sliceVal := []string{*contained}
		query["_contained"] = sliceVal
	}
	if containedType != nil {
		sliceVal := []string{*containedType}
		query["_containedType"] = sliceVal
	}
	if count != nil {
		sliceVal := []string{strconv.Itoa(*count)}
		query["_count"] = sliceVal
	}
	if elements != nil {
		sliceVal := []string{*elements}
		query["_elements"] = sliceVal
	}
	if has != nil {
		sliceVal := []string{*has}
		query["_has"] = sliceVal
	}
	if id != nil {
		sliceVal := []string{strconv.Itoa(*id)}
		query["_id"] = sliceVal
	}
	if include != nil {
		sliceVal := []string{*include}
		query["_include"] = sliceVal
	}
	if lastUpdate != nil {
		sliceVal := []string{(*lastUpdate).Format(time.RFC3339)}
		query["_lastUpdate"] = sliceVal
	}
	if list != nil {
		sliceVal := []string{*list}
		query["_list"] = sliceVal
	}
	if profile != nil {
		sliceVal := []string{*profile}
		query["_profile"] = sliceVal
	}
	if query != nil {
		sliceVal := []string{*query}
		query["_query"] = sliceVal
	}
	if revinclude != nil {
		sliceVal := []string{*revinclude}
		query["_revinclude"] = sliceVal
	}
	if security != nil {
		sliceVal := []string{*security}
		query["_security"] = sliceVal
	}
	if sort != nil {
		sliceVal := []string{*sort}
		query["_sort"] = sliceVal
	}
	if summary != nil {
		sliceVal := []string{*summary}
		query["_summary"] = sliceVal
	}
	if tag != nil {
		sliceVal := []string{*tag}
		query["_tag"] = sliceVal
	}
	if text != nil {
		sliceVal := []string{*text}
		query["_text"] = sliceVal
	}
	if type_ != nil {
		sliceVal := []string{*type_}
		query["_type"] = sliceVal
	}
	{
		sliceVal := []string{clientID}
		query["client_id"] = sliceVal
	}
	if redirectURI != nil {
		sliceVal := []string{*redirectURI}
		query["redirect_uri"] = sliceVal
	}
	{
		sliceVal := []string{responseType}
		query["response_type"] = sliceVal
	}
	if scope != nil {
		sliceVal := []string{*scope}
		query["scope"] = sliceVal
	}
	if state != nil {
		sliceVal := []string{*state}
		query["state"] = sliceVal
	}
	u := &url.URL{
		Path:     fmt.Sprintf("/nosh/oauth2/auth"),
		RawQuery: query.Encode(),
	}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		panic("invalid test " + err.Error()) // bug
	}
	prms := url.Values{}
	if contained != nil {
		sliceVal := []string{*contained}
		prms["_contained"] = sliceVal
	}
	if containedType != nil {
		sliceVal := []string{*containedType}
		prms["_containedType"] = sliceVal
	}
	if count != nil {
		sliceVal := []string{strconv.Itoa(*count)}
		prms["_count"] = sliceVal
	}
	if elements != nil {
		sliceVal := []string{*elements}
		prms["_elements"] = sliceVal
	}
	if has != nil {
		sliceVal := []string{*has}
		prms["_has"] = sliceVal
	}
	if id != nil {
		sliceVal := []string{strconv.Itoa(*id)}
		prms["_id"] = sliceVal
	}
	if include != nil {
		sliceVal := []string{*include}
		prms["_include"] = sliceVal
	}
	if lastUpdate != nil {
		sliceVal := []string{(*lastUpdate).Format(time.RFC3339)}
		prms["_lastUpdate"] = sliceVal
	}
	if list != nil {
		sliceVal := []string{*list}
		prms["_list"] = sliceVal
	}
	if profile != nil {
		sliceVal := []string{*profile}
		prms["_profile"] = sliceVal
	}
	if query != nil {
		sliceVal := []string{*query}
		prms["_query"] = sliceVal
	}
	if revinclude != nil {
		sliceVal := []string{*revinclude}
		prms["_revinclude"] = sliceVal
	}
	if security != nil {
		sliceVal := []string{*security}
		prms["_security"] = sliceVal
	}
	if sort != nil {
		sliceVal := []string{*sort}
		prms["_sort"] = sliceVal
	}
	if summary != nil {
		sliceVal := []string{*summary}
		prms["_summary"] = sliceVal
	}
	if tag != nil {
		sliceVal := []string{*tag}
		prms["_tag"] = sliceVal
	}
	if text != nil {
		sliceVal := []string{*text}
		prms["_text"] = sliceVal
	}
	if type_ != nil {
		sliceVal := []string{*type_}
		prms["_type"] = sliceVal
	}
	{
		sliceVal := []string{clientID}
		prms["client_id"] = sliceVal
	}
	if redirectURI != nil {
		sliceVal := []string{*redirectURI}
		prms["redirect_uri"] = sliceVal
	}
	{
		sliceVal := []string{responseType}
		prms["response_type"] = sliceVal
	}
	if scope != nil {
		sliceVal := []string{*scope}
		prms["scope"] = sliceVal
	}
	if state != nil {
		sliceVal := []string{*state}
		prms["state"] = sliceVal
	}
	if ctx == nil {
		ctx = context.Background()
	}
	goaCtx := goa.NewContext(goa.WithAction(ctx, "Oauth2ProviderTest"), rw, req, prms)
	authorizeCtx, err := app.NewAuthorizeOauth2ProviderContext(goaCtx, service)
	if err != nil {
		panic("invalid test data " + err.Error()) // bug
	}

	// Perform action
	err = ctrl.Authorize(authorizeCtx)

	// Validate response
	if err != nil {
		t.Fatalf("controller returned %s, logs:\n%s", err, logBuf.String())
	}
	if rw.Code != 302 {
		t.Errorf("invalid response status code: got %+v, expected 302", rw.Code)
	}

	// Return results
	return rw
}

// GetTokenOauth2ProviderBadRequest runs the method GetToken of the given controller with the given parameters and payload.
// It returns the response writer so it's possible to inspect the response headers and the media type struct written to the response.
// If ctx is nil then context.Background() is used.
// If service is nil then a default service is created.
func GetTokenOauth2ProviderBadRequest(t goatest.TInterface, ctx context.Context, service *goa.Service, ctrl app.Oauth2ProviderController, contained *string, containedType *string, count *int, elements *string, has *string, id *int, include *string, lastUpdate *time.Time, list *string, profile *string, query *string, revinclude *string, security *string, sort *string, summary *string, tag *string, text *string, type_ *string, payload *app.TokenPayload) (http.ResponseWriter, *app.OAuth2ErrorMedia) {
	// Setup service
	var (
		logBuf bytes.Buffer
		resp   interface{}

		respSetter goatest.ResponseSetterFunc = func(r interface{}) { resp = r }
	)
	if service == nil {
		service = goatest.Service(&logBuf, respSetter)
	} else {
		logger := log.New(&logBuf, "", log.Ltime)
		service.WithLogger(goa.NewLogger(logger))
		newEncoder := func(io.Writer) goa.Encoder { return respSetter }
		service.Encoder = goa.NewHTTPEncoder() // Make sure the code ends up using this decoder
		service.Encoder.Register(newEncoder, "*/*")
	}

	// Validate payload
	err := payload.Validate()
	if err != nil {
		e, ok := err.(goa.ServiceError)
		if !ok {
			panic(err) // bug
		}
		t.Errorf("unexpected payload validation error: %+v", e)
		return nil, nil
	}

	// Setup request context
	rw := httptest.NewRecorder()
	query := url.Values{}
	if contained != nil {
		sliceVal := []string{*contained}
		query["_contained"] = sliceVal
	}
	if containedType != nil {
		sliceVal := []string{*containedType}
		query["_containedType"] = sliceVal
	}
	if count != nil {
		sliceVal := []string{strconv.Itoa(*count)}
		query["_count"] = sliceVal
	}
	if elements != nil {
		sliceVal := []string{*elements}
		query["_elements"] = sliceVal
	}
	if has != nil {
		sliceVal := []string{*has}
		query["_has"] = sliceVal
	}
	if id != nil {
		sliceVal := []string{strconv.Itoa(*id)}
		query["_id"] = sliceVal
	}
	if include != nil {
		sliceVal := []string{*include}
		query["_include"] = sliceVal
	}
	if lastUpdate != nil {
		sliceVal := []string{(*lastUpdate).Format(time.RFC3339)}
		query["_lastUpdate"] = sliceVal
	}
	if list != nil {
		sliceVal := []string{*list}
		query["_list"] = sliceVal
	}
	if profile != nil {
		sliceVal := []string{*profile}
		query["_profile"] = sliceVal
	}
	if query != nil {
		sliceVal := []string{*query}
		query["_query"] = sliceVal
	}
	if revinclude != nil {
		sliceVal := []string{*revinclude}
		query["_revinclude"] = sliceVal
	}
	if security != nil {
		sliceVal := []string{*security}
		query["_security"] = sliceVal
	}
	if sort != nil {
		sliceVal := []string{*sort}
		query["_sort"] = sliceVal
	}
	if summary != nil {
		sliceVal := []string{*summary}
		query["_summary"] = sliceVal
	}
	if tag != nil {
		sliceVal := []string{*tag}
		query["_tag"] = sliceVal
	}
	if text != nil {
		sliceVal := []string{*text}
		query["_text"] = sliceVal
	}
	if type_ != nil {
		sliceVal := []string{*type_}
		query["_type"] = sliceVal
	}
	u := &url.URL{
		Path:     fmt.Sprintf("/nosh/oauth2/token"),
		RawQuery: query.Encode(),
	}
	req, err := http.NewRequest("POST", u.String(), nil)
	if err != nil {
		panic("invalid test " + err.Error()) // bug
	}
	prms := url.Values{}
	if contained != nil {
		sliceVal := []string{*contained}
		prms["_contained"] = sliceVal
	}
	if containedType != nil {
		sliceVal := []string{*containedType}
		prms["_containedType"] = sliceVal
	}
	if count != nil {
		sliceVal := []string{strconv.Itoa(*count)}
		prms["_count"] = sliceVal
	}
	if elements != nil {
		sliceVal := []string{*elements}
		prms["_elements"] = sliceVal
	}
	if has != nil {
		sliceVal := []string{*has}
		prms["_has"] = sliceVal
	}
	if id != nil {
		sliceVal := []string{strconv.Itoa(*id)}
		prms["_id"] = sliceVal
	}
	if include != nil {
		sliceVal := []string{*include}
		prms["_include"] = sliceVal
	}
	if lastUpdate != nil {
		sliceVal := []string{(*lastUpdate).Format(time.RFC3339)}
		prms["_lastUpdate"] = sliceVal
	}
	if list != nil {
		sliceVal := []string{*list}
		prms["_list"] = sliceVal
	}
	if profile != nil {
		sliceVal := []string{*profile}
		prms["_profile"] = sliceVal
	}
	if query != nil {
		sliceVal := []string{*query}
		prms["_query"] = sliceVal
	}
	if revinclude != nil {
		sliceVal := []string{*revinclude}
		prms["_revinclude"] = sliceVal
	}
	if security != nil {
		sliceVal := []string{*security}
		prms["_security"] = sliceVal
	}
	if sort != nil {
		sliceVal := []string{*sort}
		prms["_sort"] = sliceVal
	}
	if summary != nil {
		sliceVal := []string{*summary}
		prms["_summary"] = sliceVal
	}
	if tag != nil {
		sliceVal := []string{*tag}
		prms["_tag"] = sliceVal
	}
	if text != nil {
		sliceVal := []string{*text}
		prms["_text"] = sliceVal
	}
	if type_ != nil {
		sliceVal := []string{*type_}
		prms["_type"] = sliceVal
	}
	if ctx == nil {
		ctx = context.Background()
	}
	goaCtx := goa.NewContext(goa.WithAction(ctx, "Oauth2ProviderTest"), rw, req, prms)
	getTokenCtx, err := app.NewGetTokenOauth2ProviderContext(goaCtx, service)
	if err != nil {
		panic("invalid test data " + err.Error()) // bug
	}
	getTokenCtx.Payload = payload

	// Perform action
	err = ctrl.GetToken(getTokenCtx)

	// Validate response
	if err != nil {
		t.Fatalf("controller returned %s, logs:\n%s", err, logBuf.String())
	}
	if rw.Code != 400 {
		t.Errorf("invalid response status code: got %+v, expected 400", rw.Code)
	}
	var mt *app.OAuth2ErrorMedia
	if resp != nil {
		var ok bool
		mt, ok = resp.(*app.OAuth2ErrorMedia)
		if !ok {
			t.Fatalf("invalid response media: got %+v, expected instance of app.OAuth2ErrorMedia", resp)
		}
		err = mt.Validate()
		if err != nil {
			t.Errorf("invalid response media type: %s", err)
		}
	}

	// Return results
	return rw, mt
}

// GetTokenOauth2ProviderOK runs the method GetToken of the given controller with the given parameters and payload.
// It returns the response writer so it's possible to inspect the response headers and the media type struct written to the response.
// If ctx is nil then context.Background() is used.
// If service is nil then a default service is created.
func GetTokenOauth2ProviderOK(t goatest.TInterface, ctx context.Context, service *goa.Service, ctrl app.Oauth2ProviderController, contained *string, containedType *string, count *int, elements *string, has *string, id *int, include *string, lastUpdate *time.Time, list *string, profile *string, query *string, revinclude *string, security *string, sort *string, summary *string, tag *string, text *string, type_ *string, payload *app.TokenPayload) (http.ResponseWriter, *app.TokenMedia) {
	// Setup service
	var (
		logBuf bytes.Buffer
		resp   interface{}

		respSetter goatest.ResponseSetterFunc = func(r interface{}) { resp = r }
	)
	if service == nil {
		service = goatest.Service(&logBuf, respSetter)
	} else {
		logger := log.New(&logBuf, "", log.Ltime)
		service.WithLogger(goa.NewLogger(logger))
		newEncoder := func(io.Writer) goa.Encoder { return respSetter }
		service.Encoder = goa.NewHTTPEncoder() // Make sure the code ends up using this decoder
		service.Encoder.Register(newEncoder, "*/*")
	}

	// Validate payload
	err := payload.Validate()
	if err != nil {
		e, ok := err.(goa.ServiceError)
		if !ok {
			panic(err) // bug
		}
		t.Errorf("unexpected payload validation error: %+v", e)
		return nil, nil
	}

	// Setup request context
	rw := httptest.NewRecorder()
	query := url.Values{}
	if contained != nil {
		sliceVal := []string{*contained}
		query["_contained"] = sliceVal
	}
	if containedType != nil {
		sliceVal := []string{*containedType}
		query["_containedType"] = sliceVal
	}
	if count != nil {
		sliceVal := []string{strconv.Itoa(*count)}
		query["_count"] = sliceVal
	}
	if elements != nil {
		sliceVal := []string{*elements}
		query["_elements"] = sliceVal
	}
	if has != nil {
		sliceVal := []string{*has}
		query["_has"] = sliceVal
	}
	if id != nil {
		sliceVal := []string{strconv.Itoa(*id)}
		query["_id"] = sliceVal
	}
	if include != nil {
		sliceVal := []string{*include}
		query["_include"] = sliceVal
	}
	if lastUpdate != nil {
		sliceVal := []string{(*lastUpdate).Format(time.RFC3339)}
		query["_lastUpdate"] = sliceVal
	}
	if list != nil {
		sliceVal := []string{*list}
		query["_list"] = sliceVal
	}
	if profile != nil {
		sliceVal := []string{*profile}
		query["_profile"] = sliceVal
	}
	if query != nil {
		sliceVal := []string{*query}
		query["_query"] = sliceVal
	}
	if revinclude != nil {
		sliceVal := []string{*revinclude}
		query["_revinclude"] = sliceVal
	}
	if security != nil {
		sliceVal := []string{*security}
		query["_security"] = sliceVal
	}
	if sort != nil {
		sliceVal := []string{*sort}
		query["_sort"] = sliceVal
	}
	if summary != nil {
		sliceVal := []string{*summary}
		query["_summary"] = sliceVal
	}
	if tag != nil {
		sliceVal := []string{*tag}
		query["_tag"] = sliceVal
	}
	if text != nil {
		sliceVal := []string{*text}
		query["_text"] = sliceVal
	}
	if type_ != nil {
		sliceVal := []string{*type_}
		query["_type"] = sliceVal
	}
	u := &url.URL{
		Path:     fmt.Sprintf("/nosh/oauth2/token"),
		RawQuery: query.Encode(),
	}
	req, err := http.NewRequest("POST", u.String(), nil)
	if err != nil {
		panic("invalid test " + err.Error()) // bug
	}
	prms := url.Values{}
	if contained != nil {
		sliceVal := []string{*contained}
		prms["_contained"] = sliceVal
	}
	if containedType != nil {
		sliceVal := []string{*containedType}
		prms["_containedType"] = sliceVal
	}
	if count != nil {
		sliceVal := []string{strconv.Itoa(*count)}
		prms["_count"] = sliceVal
	}
	if elements != nil {
		sliceVal := []string{*elements}
		prms["_elements"] = sliceVal
	}
	if has != nil {
		sliceVal := []string{*has}
		prms["_has"] = sliceVal
	}
	if id != nil {
		sliceVal := []string{strconv.Itoa(*id)}
		prms["_id"] = sliceVal
	}
	if include != nil {
		sliceVal := []string{*include}
		prms["_include"] = sliceVal
	}
	if lastUpdate != nil {
		sliceVal := []string{(*lastUpdate).Format(time.RFC3339)}
		prms["_lastUpdate"] = sliceVal
	}
	if list != nil {
		sliceVal := []string{*list}
		prms["_list"] = sliceVal
	}
	if profile != nil {
		sliceVal := []string{*profile}
		prms["_profile"] = sliceVal
	}
	if query != nil {
		sliceVal := []string{*query}
		prms["_query"] = sliceVal
	}
	if revinclude != nil {
		sliceVal := []string{*revinclude}
		prms["_revinclude"] = sliceVal
	}
	if security != nil {
		sliceVal := []string{*security}
		prms["_security"] = sliceVal
	}
	if sort != nil {
		sliceVal := []string{*sort}
		prms["_sort"] = sliceVal
	}
	if summary != nil {
		sliceVal := []string{*summary}
		prms["_summary"] = sliceVal
	}
	if tag != nil {
		sliceVal := []string{*tag}
		prms["_tag"] = sliceVal
	}
	if text != nil {
		sliceVal := []string{*text}
		prms["_text"] = sliceVal
	}
	if type_ != nil {
		sliceVal := []string{*type_}
		prms["_type"] = sliceVal
	}
	if ctx == nil {
		ctx = context.Background()
	}
	goaCtx := goa.NewContext(goa.WithAction(ctx, "Oauth2ProviderTest"), rw, req, prms)
	getTokenCtx, err := app.NewGetTokenOauth2ProviderContext(goaCtx, service)
	if err != nil {
		panic("invalid test data " + err.Error()) // bug
	}
	getTokenCtx.Payload = payload

	// Perform action
	err = ctrl.GetToken(getTokenCtx)

	// Validate response
	if err != nil {
		t.Fatalf("controller returned %s, logs:\n%s", err, logBuf.String())
	}
	if rw.Code != 200 {
		t.Errorf("invalid response status code: got %+v, expected 200", rw.Code)
	}
	var mt *app.TokenMedia
	if resp != nil {
		var ok bool
		mt, ok = resp.(*app.TokenMedia)
		if !ok {
			t.Fatalf("invalid response media: got %+v, expected instance of app.TokenMedia", resp)
		}
		err = mt.Validate()
		if err != nil {
			t.Errorf("invalid response media type: %s", err)
		}
	}

	// Return results
	return rw, mt
}
